application: ${project.name}
version: ${project.version}
runtime: java

handlers:
- url: /admin
  jsp: admin.jsp
  login: admin
  secure: always
  name: admin
- url: /report
  servlet: com.github.wreckan.server.ReportServlet
  secure: always
  name: report
- url: /gwtRequest
  servlet: com.google.web.bindery.requestfactory.server.RequestFactoryServlet
  secure: always
  name: gwtRequest
   
inbound_services:
- mail

threadsafe: false
